# Generated by Django 4.2 on 2023-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("record_date", models.DateField()),
                ("max_temp", models.SmallIntegerField()),
                ("min_temp", models.SmallIntegerField()),
                ("precipitation_amount", models.SmallIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "unique_together": {("location", "record_date")},
            },
        ),
    ]
