# Generated by Django 4.2 on 2023-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherAggregatedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("year", models.SmallIntegerField()),
                ("avg_max_temp", models.SmallIntegerField()),
                ("avg_min_temp", models.SmallIntegerField()),
                ("sum_precipitation_amount", models.SmallIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "unique_together": {("location", "year")},
            },
        ),
    ]
