# Generated by Django 4.2 on 2023-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_weatheraggregateddata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatheraggregateddata",
            name="avg_max_temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatheraggregateddata",
            name="avg_min_temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatheraggregateddata",
            name="sum_precipitation_amount",
            field=models.FloatField(),
        ),
    ]
